"""Official Miaoshou OpenAPI paths (TikTok collect box + common)."""
FETCH_ITEM = "/open/v1/product/common_collect_box/common_collect_box/fetch_item"
PUBLIC_LIST = "/open/v1/product/common_collect_box/common_collect_box/get_common_collect_box_list"
PUBLIC_DETAIL = "/open/v1/product/common_collect_box/common_collect_box/get_common_collect_box_detail"
CLAIM_PUBLIC = "/open/v1/product/common_collect_box/common_collect_box/claimed"
SHOP_LIST = "/open/v1/product/shop/shop/get_shop_list"

TIKTOK_LIST = "/open/v1/product/collect_box/tiktok/collect_box/search_collect_box_detail_list"
CLAIM_TO_SHOP = "/open/v1/product/collect_box/tiktok/collect_box/claim_to_shop"
GET_SHOP_DETAIL = "/open/v1/product/collect_box/tiktok/collect_box/get_shop_collect_item_info"
SAVE_SHOP_DETAIL = "/open/v1/product/collect_box/tiktok/collect_box/save_shop_collect_item_info"
GET_SITE_DETAIL = "/open/v1/product/collect_box/tiktok/collect_box/get_site_collect_item_info"
SAVE_SITE_DETAIL = "/open/v1/product/collect_box/tiktok/collect_box/save_site_collect_item_info"
CATEGORY_META = "/open/v1/product/collect_box/tiktok/collect_box/get_category_metadata"
CATEGORY_TREE = "/open/v1/product/collect_box/tiktok/collect_box/get_category_tree_by_site"
SHOP_WAREHOUSE_LIST = "/open/v1/product/collect_box/tiktok/collect_box/get_shop_warehouse_list"
MANUFACTURER_LIST = "/open/v1/product/collect_box/tiktok/collect_box/get_manufacturer_list"
RESPONSIBLE_PERSON_LIST = "/open/v1/product/collect_box/tiktok/collect_box/get_responsible_person_list"
BRAND_LIST = "/open/v1/product/collect_box/tiktok/collect_box/get_brand_list"
PUBLISH = "/open/v1/product/collect_box/tiktok/collect_box/save_move_collect_task"
PUBLISH_LIST = "/open/v1/product/collect_box/tiktok/move_collect/search_move_collect_list"
